[flake8]

# E302 - Two blank lines after a function.
ignore = E731, E302, E306
max-line-length = 160

[coverage:run]
branch = True
source = farmfs
parallel = True

[coverage:paths]
source =
    .
    */site-packages
