from collections.abc import Callable, Iterable
from os import mkdir, stat_result
from os import listdir
from os import link
from os import unlink
from os import symlink
from os import readlink
from os import rmdir
from os import stat
from os import chmod
from os import rename
from os import lstat
from errno import ENOENT as FileDoesNotExist
from errno import EEXIST as FileExists
from errno import EISDIR as DirectoryExists
from errno import EINVAL as InvalidArgument
from errno import EPERM as NotPermitted
from errno import EISDIR as IsADirectory
from hashlib import md5
from os.path import exists
from os.path import isabs
from os.path import isdir
from os.path import isfile, islink, sep
from os.path import normpath
from os.path import split
import stat as statc
from os.path import splitext
from fnmatch import fnmatchcase
from functools import total_ordering
from typing import IO, Any, Generator, List, Protocol, Optional, Tuple, Union
from farmfs.util import (
    ingest,
    uncurry,
    first,
    second,
    ffilter,
    copyfileobj,
    reducefileobj,
)
from safeoutput import open as safeopen
from safeoutput import _sameDir as sameDir  # TODO using hidden function.
from filetype import guess, Type
import filetype

ERRORS = [
    FileDoesNotExist,
    FileExists,
    DirectoryExists,
    InvalidArgument,
    NotPermitted,
    IsADirectory,
]


class XSym(Type):
    """Implements OSX XSym link file type detector"""

    def __init__(self):
        super(XSym, self).__init__(mime="inode/symlink", extension="xsym")

    def match(self, buf: bytes) -> bool:
        """
        Detects the MS-Dos symbolic link format from OSX.
        Format of XSym files taken from section 11.7.3 of Mac OSX Internals
        """
        X = 0x58
        S = 0x53
        Y = 0x79
        M = 0x6D
        NEWLINE = 0xA
        ZERO = 0x30
        NINE = 0x39
        return (
            len(buf) >= 10
            and buf[0] == X
            and buf[1] == S
            and buf[2] == Y
            and buf[3] == M
            and buf[4] == NEWLINE
            and buf[5] >= ZERO
            and buf[5] <= NINE
            and buf[6] >= ZERO
            and buf[6] <= NINE
            and buf[7] >= ZERO
            and buf[7] <= NINE
            and buf[8] >= ZERO
            and buf[8] <= NINE
            and buf[9] == NEWLINE
        )


# XXX Dirty, we are touching the set of types in filetype package.
filetype.types.append(XSym())

_BLOCKSIZE = 65536

LINK = "link"
FILE = "file"
DIR = "dir"

TYPES = [LINK, FILE, DIR]


def ignored_path_checker(ignored: Iterable[str]) -> Callable[["Path"], bool]:

    ign = tuple(ignored)

    def is_ignored_path(path: "Path") -> bool:
        for i in ign:
            if fnmatchcase(path._path, i):
                return True
        else:
            return False
    return is_ignored_path


def ftype_selector(keep_types: List[str]
                   ) -> Callable[[Iterable["WalkItem"]], Iterable["WalkItem"]]:
    def keep(p: "Path", ft: str) -> bool:
        return ft in keep_types
    keep_uncurried: Callable[[WalkItem], bool] = uncurry(keep)
    return ffilter(keep_uncurried)

# Hashlib doesn't have a public type for hash objects as of Python3.12.
# Until this is fixed, we have to define our own protocl which matches the public API
# of hash objects.
class HashLike(Protocol):
    def update(self, data: bytes) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...

def _hash_buff(hasher: HashLike, buf: bytes) -> HashLike:
    hasher.update(buf)
    return hasher

def _md5() -> HashLike:
    """Wrapper for md5 constructor to avoid type issues with the hashlib module."""
    return md5()

def canonicalPath(path: str) -> str:
    """
    Takes a path string as input.
    Normalizes the path sot that it can be compared with other paths canonocally.
    Behaves like normpath, but also reduces leading double slashes into a single slash.
    """
    norm = normpath(path)
    if norm.startswith("//"):
        return norm[1:]
    return norm


@total_ordering
class Path:

    _path : str
    _parent: Optional["Path"]

    def __init__(self, path: Union[str, "Path"], frame: Optional["Path"] = None, fast: bool = False):
        # output = Path( self._path + sep + child)
        if fast:
            # Fast path is generated by walk. frame is already a Path and path is a single element from listdir.
            assert isinstance(frame, Path)
            assert isinstance(path, str)
            self._path = frame._path + sep + path
            self._parent = frame
        elif isinstance(path, Path): # Slow but we are just copying from path param.
            # Copy constructor from another Path.
            assert frame is None
            self._path = path._path
            self._parent = path._parent
        else: # Slow and we are building relative to some frame.
            if path is None: # TODO should not happen.
                raise ValueError("path must be defined")
            path_str = ingest(path)
            if frame is None:
                self._path = canonicalPath(path_str)
                assert self._path.startswith(sep), (
                    "Frame is required when building relative paths: %s" % path
                )
            else:
                assert isinstance(frame, Path)
                assert not path.startswith(sep), (
                    "path %s is required to be relative when a frame %s is provided"
                    % (path, frame)
                )
                self._path = canonicalPath(frame._path + sep + path)
            self._parent = None
        assert isinstance(self._path, str)

    def __str__(self) -> str:
        return self._path

    def __repr__(self) -> str:
        return str(self)

    def mkdir(self) -> None:
        try:
            mkdir(self._path)
        except OSError as e:
            if e.errno == FileExists:
                pass
            else:
                raise e

    def parent(self) -> Optional["Path"]:
        """
        Returns the parent of self. If self is root ('/'), parent returns None.
        You much check the output of parent before using the value.
        Notcie that parent of root in the shell is '/', so this is a semantic difference
        between FarmFS and POSIX.
        """
        if self._path == sep:
            return None
        elif self._parent is None:
            parent_str, name_str = split(self._path)
            self._parent = Path(parent_str)
            return self._parent
        else:
            return self._parent

    def parents(self) -> Iterable["Path"]:
        # TODO turn into comprehension.
        paths = [self]
        path = self
        parent = path.parent()
        while parent is not None:
            paths.append(parent)
            path = parent
            parent = path.parent()
        return reversed(paths)

    def name(self) -> str:
        parent_str, name_str = split(self._path)
        return name_str

    def extension(self) -> Optional[str]:
        root, ext = splitext(self._path)
        if ext == "":
            return None
        return ext

    def relative_to(self, frame: "Path") -> str:
        assert isinstance(frame, Path)
        # Fast mode check for normalized path decendents.
        if (
            len(self._path) >= len(frame._path) + 2
            and self._path.startswith(frame._path)
            and self._path[len(frame._path) + 1] == sep
        ):
            return self._path[len(frame._path):]
        # Get the segment sequences from root to self and frame.
        self_family = iter(self.parents())
        frame_family = iter(frame.parents())
        # Find the common ancesstor of self and frame.
        s = None
        f = None
        common = None
        while True:
            s = next(self_family, None)
            f = next(frame_family, None)
            if s is None and f is None:
                if common is None:
                    # common should have at least advanced to root!
                    raise ValueError(
                        "Failed to find common decendent of %s and %s" % (self, frame)
                    )
                else:
                    # self and frame exhaused at the same time. Must be the same path.
                    return SELF_STR
            elif s is None:
                # frame is a decendent of self. Self is an ancesstor of frame.
                # We can return remaining segments of frame.
                # Self is "/a" frame = "/a/b/c" common is "/a" result is "../.."
                backtracks = len(list(frame_family)) + 1
                backtrack_arr = [PARENT_STR] * backtracks
                backtrack = sep.join(backtrack_arr)
                # raise NotImplementedError("self %s frame %s common %s backtracks %s backtrack %s" % (
                #    self, frame, common, backtracks, backtrack))
                return backtrack
            elif f is None:
                # self is a decendent of frame. frame is an ancesstor of self.
                # We can return remaining segments of self.
                assert common == frame
                assert common is not None
                return self._path[len(common._path) + 1:]
            elif s == f:
                # self and frame decendent are the same, so advance.
                common = s
                pass
            else:
                # we need to backtrack from frame to common.
                backtracks = len(list(frame_family)) + 1
                backtrack_arr = [PARENT_STR] * backtracks
                backtrack = sep.join(backtrack_arr)
                if common == ROOT:
                    forward = self._path[len(common._path):]
                else:
                    assert common is not None
                    forward = self._path[len(common._path) + 1:]
                # print("backtracks", backtracks, "backtrack", backtrack, "forward", forward, "common", common)
                return backtrack + sep + forward

    def exists(self) -> bool:
        """Returns true if a path exists. This includes symlinks even if they are broken."""
        return self.islink() or exists(self._path)

    def readlink(self, frame=None) -> "Path":
        """
        Returns the link destination if the Path is a symlink.
        If the path doesn't exist, raises FileNotFoundError
        If the path is not a symlink raises OSError Errno InvalidArgument.
        """
        return Path(readlink(self._path), frame)

    def link(self, dst: "Path") -> None:
        """
        Creates a hard link to dst.
              dst
              DNE Dir F   SLF SLD SLB
        s DNR  R   R   N   N   R   R
        e Dir  R   R   R   R   R   R
        l F    R   R   R   R   ?   ?
        f SL   R   R   R   R   ?   ?
        R means raises.
        N means new hardlink created.
        """
        assert isinstance(dst, Path)
        link(dst._path, self._path)

    def symlink(self, dst: "Path") -> None:
        """
        self is created as a symlink to the path dst.
        dst is the target of the new symlink.
        """
        assert isinstance(dst, Path)
        symlink(dst._path, self._path)

    def copy_fd(self, src_fd: Union[IO[bytes], IO[str]], tmpdir: Optional["Path"] = None) -> None:
        """
        Reads src_fd and puts the contents into a file located at self._path.
        """
        if tmpdir is None:
            tmpfn = sameDir
        else:
            tmpfn = lambda _: tmpdir._path
        mode = "w"
        if hasattr(src_fd, "mode"):
            if "b" in src_fd.mode:
                mode += "b"
        else:
            mode += "b"  # http clients use bytes.
        with safeopen(self._path, mode, useDir=tmpfn) as dst_fd:
            copyfileobj(src_fd, dst_fd)

    # TODO this behavior is the opposite of what one would expect.
    def copy_file(self, dst: "Path", tmpdir: Optional["Path"] = None) -> None:
        """
        Copy self to path dst.
        Does not attempt to ensure dst is a valid destination.
        Raises IsADirectoryError and FileDoesNotExist on namespace errors.
        The file will either be fully copied, or will not be created.
        This is achieved via temp files and atomic swap.
        This API works for large files, as data is read in chunks and sent
        to the destination.
        """
        if tmpdir is None:
            tmpfn = sameDir
        else:
            tmpfn = lambda _: tmpdir._path
        assert isinstance(dst, Path)
        with open(self._path, "rb") as src_fd:
            with safeopen(dst._path, "wb", useDir=tmpfn) as dst_fd:
                copyfileobj(src_fd, dst_fd)

    def unlink(self, clean: Optional["Path"]=None) -> None:
        try:
            unlink(self._path)
        except OSError as e:
            if e.errno == FileDoesNotExist:
                pass
            else:
                raise e
        if clean is not None:
            parent = self.parent()
            if parent is not None:
                parent._cleanup(clean)

    def rmdir(self, clean: Optional["Path"]=None) -> None:
        rmdir(self._path)
        if clean is not None:
            parent = self.parent()
            if parent is not None:
                parent._cleanup(clean)

    """Called on the parent of file or directory after a removal
    (if cleanup as asked for). Recuses cleanup until it reaches terminus.
    """

    def _cleanup(self, terminus: "Path") -> None:
        assert isinstance(terminus, Path)
        assert terminus in self.parents()
        if self == terminus:
            return
        if len(self.dir_list()) == 0:
            self.rmdir(terminus)

    def islink(self) -> bool:
        return islink(self._path)

    def isdir(self) -> bool:
        return isdir(self._path)

    def isfile(self) -> bool:
        return isfile(self._path)

    def checksum(self) -> str:
        """
        If self path is a file or a symlink to a file, compute a checksum returned as a string.
        If self points to a missing file or a broken symlink, raises FileDoesNotExist.
        If self points to a directory or a symlink facing directory, raises IsADirectory.
        """
        with self.open("rb") as fd:
            hash = reducefileobj(_hash_buff, fd, _md5(), _BLOCKSIZE)
        digest = str(hash.hexdigest())
        return digest

    def __cmp__(self, other: "Path") -> int:
        return (self > other) - (self < other)

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, Path):
            return NotImplemented
        return self._path == other._path

    def __ne__(self, other: Any) -> bool:
        if not isinstance(other, Path):
            return NotImplemented
        return not (self == other)

    def __lt__(self, other: Any) -> bool:
        if not isinstance(other, Path):
            return NotImplemented
        self_segments = self._path.split(sep)
        other_segments = other._path.split(sep)
        return self_segments < other_segments

    def __hash__(self) -> int:
        return hash(self._path)

    # TODO join looks broken to me. If we had a path, it would be "/a/b/c"
    # and then output would be "/self/path/segs//a/b/c"
    # and be normalized to "/self/path/segs/a/b/c" which might not be what was expected.
    def join(self, child: str) -> "Path":
        child = str(child)
        output = Path(self._path + sep + child)
        return output

    def dir_list(self) -> List["Path"]:
        names = sorted(listdir(self._path))
        paths = [Path(n, self, fast=True) for n in names]
        return paths

    # TODO ftype could become a Literal.
    def ftype(self) -> str:
        st = lstat(self._path)
        if statc.S_ISLNK(st.st_mode):
            return LINK
        elif statc.S_ISREG(st.st_mode):
            return FILE
        elif statc.S_ISDIR(st.st_mode):
            return DIR
        else:
            raise ValueError("%s is not in %s" % (self, TYPES))

    # TODO need a way to express that "b" modes get IO[bytes] otherwise IO[str].
    def open(self, mode: str) -> Union[IO[bytes], IO[str]]:
        return open(self._path, mode)

    # TODO need a way to express that "b" modes get IO[bytes] otherwise IO[str].
    def content(self, mode: str) -> Union[str, bytes]:
        """Helper function to quickly read file contents into a string. Should be used for small files only"""
        with self.open(mode) as fd:
            return fd.read()

    def safeopen(self, mode: str, tmpfn: Optional[Callable[["Path"], "Path"]] = None):
        if tmpfn is None:
            return safeopen(self._path, mode)
        else:
            return safeopen(self._path, mode, useDir=lambda p: tmpfn(p)._path)

    def read_chunks(self, size: int) -> Generator[bytes, None, None]:
        """
        Returns a generator which reads the file in size chunks.
        A file handle is allocated before the first chunk is read.
        """
        fd = self.open("rb")

        def read_generator() -> Generator[bytes, None, None]:
            with fd:
                while True:
                    chunk = fd.read(size)
                    if not chunk:
                        break
                    yield chunk

        return read_generator()

    def stat(self) -> stat_result:
        return stat(self._path)

    def chmod(self, mode: int) -> None:
        return chmod(self._path, mode)

    def rename(self, dst: "Path") -> None:
        return rename(self._path, dst._path)

    def filetype(self):
        with self.open("rb") as fd:
            type = guess(bytearray(fd.read(256)))
            if type:
                return type.mime
            else:
                return None


# TODO userPath2Path should not need to take bytes. Change it and see what breaks.
def userPath2Path(arg: str | bytes, frame: Path) -> Path:
    """
    Building paths using conventional POSIX systems will discard CWD if the
    path is absolute. FarmFS makes passing of CWD explicit so that path APIs
    are pure functions. Additionally FarmFS path construction doesn't allow
    for absolute paths to be mixed with frames. This is useful for
    spotting bugs and making sure that pathing has strong guarantees. However
    this comes at the expense of user expectation. When dealing with user
    input, there is an expecation that POSIX semantics are at play.
    userPath2Path checks to see if the provided path is absolute, and if not,
    adds the CWD frame.
    """
    arg = ingest(arg)
    if isabs(arg):
        return Path(arg)
    else:
        return Path(arg, frame)


# TODO this function is dangerous. Would be better if we did sorting in the snaps to ensure order of ops explicitly.
def ensure_absent(path: Path) -> None:
    if path.exists():
        if path.isdir():
            for child in path.dir_list():
                ensure_absent(child)
            path.rmdir()
        else:
            path.unlink()
    else:
        pass  # No work to do.


def ensure_dir(path: Path) -> None:
    if path.exists():
        if path.isdir():
            pass  # There is nothing to do.
        else:
            path.unlink()
            path.mkdir()
    else:
        assert path != ROOT, "Path is root, which must be a directory"
        parent = path.parent()
        assert parent != path, "Path and parent were the same!"
        ensure_dir(parent)
        path.mkdir()


def ensure_link(path: Path, orig: Path) -> None:
    assert orig.exists()
    parent = path.parent()
    assert parent != path, "Path and parent were the same!"
    ensure_dir(parent)
    ensure_absent(path)
    path.link(orig)


WRITE_MASK = statc.S_IWUSR | statc.S_IWGRP | statc.S_IWOTH  # 0o222
PERM_BITS = statc.S_IRWXU | statc.S_IRWXG | statc.S_IRWXO  # 0o777


def ensure_readonly(path: Path) -> None:
    mode = path.stat().st_mode & PERM_BITS
    new_mode = mode & ~WRITE_MASK
    path.chmod(new_mode)


# TODO this is used only for fsck readonly check.
def is_readonly(path: Path) -> bool:
    mode = path.stat().st_mode & PERM_BITS
    return not bool(mode & WRITE_MASK)


def ensure_copy(dst: Path, src: Path, tmpdir: Optional[Path] = None) -> None:
    assert src.exists()
    parent = dst.parent()
    assert parent != dst, "dst and parent were the same!"
    ensure_dir(parent)
    ensure_absent(dst)
    src.copy_file(dst, tmpdir)


def ensure_copy_fd(dst: Path, src_fd: IO[bytes] | IO[str], tmpdir: Optional[Path] = None) -> None:
    parent = dst.parent()
    assert parent is not None, "dst has no parent, cannot copy to root!"
    assert parent != dst, "dst and parent were the same!"
    ensure_dir(parent)
    ensure_absent(dst)
    dst.copy_fd(src_fd, tmpdir)


def ensure_rename(dst: Path, src: Path) -> None:
    src_parents = src.parents()
    dst_parents = dst.parents()
    if dst._path == src._path:
        return  # No work to do.
    elif src in dst_parents:
        raise ValueError("src %s is a decendent of dst %s" % (src, dst))
    elif dst in src_parents:
        raise ValueError("dst %s is a decendent of src %s" % (dst, src))
    else:
        parent = dst.parent()
        assert parent is not None, "parent is None, so dst is root. Cannot rename to root!"
        ensure_dir(parent)
        ensure_absent(dst)
        src.rename(dst)


def ensure_symlink(path: Path, target: Path) -> None:
    ensure_symlink_unsafe(path, target._path)


def ensure_symlink_unsafe(path: Path, orig: str) -> None:
    parent = path.parent()
    assert parent is not None, "path has no parent, so path is root. Cannot symlink root!"
    assert parent != path, "Path and parent were the same!"
    ensure_dir(parent)
    ensure_absent(path)
    assert not path.exists()
    symlink(orig, path._path)
    assert path.islink()


# TODO need a way to express that "b" modes get IO[bytes] otherwise IO[str].
def ensure_file(path: Path, mode: str) -> Union[IO[bytes], IO[str]]:
    """
    Creates/Deletes directories. Does whatever is required inorder
    to make and open a file with the mode previded.

    Mode settings to consider are:
     O_CREAT         create file if it does not exist
     O_TRUNC         truncate size to 0
     O_EXCL          error if O_CREAT and the file exists
    """
    assert isinstance(path, Path)
    parent = path.parent()
    assert parent is not None, "path has no parent, so path is root. Cannot create root as a file!"
    assert parent != path, "Path and parent were the same!"
    ensure_dir(parent)
    fd = path.open(mode)
    return fd


# TODO these could be a literal.
ROOT = Path(sep)
PARENT_STR = str("..")
SELF_STR = str(".")


SkipFunction = Callable[[Path], bool]
# TODO str could be a literal ROOT
WalkItem = Tuple[Path, str]

def walk(
        *roots: Path,
        skip: Optional[SkipFunction] = None
        ) -> Generator[WalkItem, None, None]:
    if skip is None:
        skip = lambda p: False
    dirs = [iter(sorted(roots))]
    while len(dirs) > 0:
        curDir = dirs[-1]
        curPath = next(curDir, None)
        if curPath is None:
            dirs.pop()
        else:
            type = curPath.ftype()
            if skip(curPath):
                continue
            yield (curPath, type)
            if type is DIR:
                children = curPath.dir_list()
                dirs.append(iter(children))

def walk_path(item: WalkItem) -> Path:
    return item[0]

def walk_type(item: WalkItem) -> str:
    return item[1]